# docker-compose.yml file
version: '3'

services:
  # The load balancer
  nginx:
    container_name: nginx
    image: nginx:1.16.0-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
networks:
  default:
    external:
      name: 'home'